pipeline{
        agent any
        // environment {
        //     DB_PASSWORD="1234dfghj"
        // }
        stages{
            stage('Clone Repo'){
                steps{
                    git 'https://gitlab.com/qacdevops/chaperootodo_client.git'
                    echo 'Repo succesfully cloned'
                }
            }
            stage('Install Docker & Docker Compose'){
                steps{
                    sh '''sudo apt-get update
                    sudo apt install curl -y
                    curl https://get.docker.com | sudo bash
                    sudo usermod -aG docker \$(whoami)
                    sudo usermod -aG jenkins \$(whoami)
                    sudo apt-get update
                    sudo apt install -y curl jq
                    sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
                    '''
                    echo 'Docker & Docker Compose succesfully installed'
                }
            }
            stage('Deploy'){
                steps{
                    withCredentials([string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD')]) {
                        sh 'sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d'
                        }
                    echo 'Deployment successful'
                }
            }
        }
}