pipeline{
        agent any
        stages{
            stage('Clone Repo'){
                steps{
                    sh "git clone https://gitlab.com/qacdevops/chaperootodo_client && sudo useradd -m -s /bin/bash jenkins"
                }
            }
            stage('Install Docker & Docker Compose'){
                steps{
                    sh "curl https://get.docker.com | sudo bash && sudo apt install -y curl jq"
                }
            }
            stage('Deploy'){
                steps{
                    sh "sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d"
                }
            }
        }
}